name: Audit & Dashboard
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - "**/*.ts"
      - "**/*.spec.ts"
      - scripts/**
  workflow_dispatch: null
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install npm
        run: npm install
      - name: Install dependencies
        run: npm ci
      - name: Run audit generation
        run: npm run generate-audit
      - name: Commit audit files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add audit/audit.json audit/dashboard.html
          git commit -m "chore: update audit dashboard" || echo "No changes"
          git push
